on:
  workflow_dispatch:
    inputs:
      ZIGVER:
        description: "zig version to target"
        required: true

run-name: '${{ inputs.ZIGVER }}'
jobs:
  do_the_thing:
    runs-on: ubuntu-latest
    steps:
      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ inputs.ZIGVER }}
          use_cache: false
      - run: timeout 1m zig init
      - run: timeout 1m zig build
      - run: timeout 1m zig build run
